[package]
name = "fix-layout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
breadx = "3.1.0"
regex = "1.10.2"
thiserror = "1.0.50"
